---
language: node_js
node_js:
  - "7"

sudo: false
cache: yarn

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH

install:
  - npm install -g bower
  - yarn install
  - bower install

script:
  - npm run test:node && ember try:one $EMBER_TRY_SCENARIO test
